# Generated by Django 4.2.30 on 2026-09-21 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_expense_number_of_people_expense_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='trip',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='travel.trip'),
            preserve_default=False,
        ),
    ]
