# Generated by Django 4.2.30 on 2026-09-21 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_alter_expense_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='filled_seats',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trip',
            name='total_seats',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='trip',
            name='vehicle_type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
