# Generated by Django 4.2.30 on 2026-09-21 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_trip_filled_seats_trip_total_seats_trip_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='filled_seats',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='total_seats',
            field=models.PositiveIntegerField(blank=True, default=4, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
