# Generated by Django 4.2.30 on 2026-09-21 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_alter_trip_filled_seats_alter_trip_total_seats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
