# Generated by Django 4.2.30 on 2026-09-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0008_triprequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='filled_seats',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trip',
            name='total_seats',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='trip',
            name='vehicle_type',
            field=models.CharField(choices=[('vehicle', 'Has Vehicle'), ('passenger', 'No Vehicle')], default='passenger', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='triprequest',
            constraint=models.UniqueConstraint(fields=('trip', 'sender'), name='unique_trip_request'),
        ),
    ]
