# Generated by Django 4.2.30 on 2026-09-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0009_alter_trip_filled_seats_alter_trip_total_seats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
