# Generated by Django 4.2.30 on 2026-09-23 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0010_alter_trip_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='travel_role',
            field=models.CharField(choices=[('vehicle', 'Has Vehicle'), ('passenger', 'Passenger')], default='passenger', max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='travel.trip'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='total_seats',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
