# Generated by Django 4.2.30 on 2026-09-23 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0011_trip_travel_role_alter_expense_trip_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='travel_role',
        ),
        migrations.AlterField(
            model_name='trip',
            name='filled_seats',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='trip',
            name='total_seats',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='trip',
            name='vehicle_type',
            field=models.CharField(choices=[('vehicle', 'Has Vehicle'), ('passenger', 'No Vehicle')], default='passenger', max_length=20),
        ),
    ]
